### ISSUE TITLE
Is buffer write supported?

### ISSUE THREAD

**Issue by yafacex** [stevensona/shader-toy#58] opened 2019-06-19 12:05 UTC
https://www.shadertoy.com/view/ldyfDG

[bufferA.glsl.txt](https://github.com/stevensona/shader-toy/files/3305968/bufferA.glsl.txt)

it reports:
“GLSL Preview”: Maximum call stack size exceeded。

**Comment by Malacath-92** [comment] 2019-06-19 12:22
If you want to feedback into the same buffer use the "target" self. Also if you are on the newest version I would suggest you to use the more standard syntax
```#iChannel0 "file:\\self"```
The way you are doing it is deprecated and will be removed eventually. Presumably in version 1.0

**Comment by Malacath-92** [comment] 2019-06-19 18:56
I tested your shader locally using the above line of code. The result is as expected, compared to the online version. But I noticed that the screenshot function seems to not handle this shader very well, so that is a new todo  :)
![shadertoy](https://user-images.githubusercontent.com/30243536/59792444-809cea00-92d4-11e9-9d73-789cf9e16cf4.png)

**Comment by yafacex** [comment] 2019-06-20 07:21
I have tried what you suggest.But still not work.(Vscode Version 1.35.1)In Developer console.I see errors as below:

(node:5684) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERR Method not implemented.: Error: Method not implemented.
	at GLSLLintingProvider.provideCodeActions (C:\Users\Administrator\.vscode\extensions\cadenas.vscode-glsllint-0.0.5\out\src\features\glsllintProvider.js:89:15)

**Comment by Malacath-92** [comment] 2019-06-20 07:26
Wow, I have never seen these kinds of error messages. What system are you running on?

**Comment by Malacath-92** [comment] 2019-06-20 07:34
@yafacex Are you sure this is our issue? I just realized the path specified is part of the `glsllint` extension. Try disabling that extension and see if it works then.
If it does, try reenabling it and wrapping your channel definitions inside and ifdef like so:
```
#ifdef SHADER_TOY
#iChannel0 "file://self"
#endif
```

**Comment by yafacex** [comment] 2019-06-20 08:36
Still not work.I tried another https://www.shadertoy.com/view/llBBRz . It just ouputs blank white.I got some openGL errors.
[bufferA2.glsl.txt](https://github.com/stevensona/shader-toy/files/3309512/bufferA2.glsl.txt)

[Embedded Page] [.Offscreen-For-WebGL-00000000058694B0]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
workbench.main.js:3551 [Embedded Page] [.Offscreen-For-WebGL-00000000058694B0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
workbench.main.js:3551 [Embedded Page] THREE.WebGLRenderer: Texture is not power of two. Texture.wrapS and Texture.wrapT should be set to THREE.ClampToEdgeWrapping.

**Comment by yafacex** [comment] 2019-06-20 08:52
> Still not work(Windows7 Vscode 1.35.1).I tried another https://www.shadertoy.com/view/llBBRz . It just ouputs blank white.I got some openGL errors.
> [bufferA2.glsl.txt](https://github.com/stevensona/shader-toy/files/3309512/bufferA2.glsl.txt)
> 
> [Embedded Page] [.Offscreen-For-WebGL-00000000058694B0]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
> workbench.main.js:3551 [Embedded Page] [.Offscreen-For-WebGL-00000000058694B0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
> workbench.main.js:3551 [Embedded Page] THREE.WebGLRenderer: Texture is not power of two. Texture.wrapS and Texture.wrapT should be set to THREE.ClampToEdgeWrapping.

I tried a simple one .It also outputs these errors,but result is right.I will test more later...

**Comment by Malacath-92** [comment] 2019-06-20 09:07
> I tried another https://www.shadertoy.com/view/llBBRz
This outputs plain white for me on the online version as well. So I'm not too surprised.

The other problems are _only_ warnings. I can look into them, but they shouldn't cause these issues.

**Comment by yafacex** [comment] 2019-06-20 12:43
I'm sorry for that.I put three examples here in zip file : main1.glsl , main2.glsl,  main3.glsl. All use buffer feature.Only main1.glsl works fine.The shadertoy link address is at top of the each file.Maybe I write something wrong?
[shadertoy.zip](https://github.com/stevensona/shader-toy/files/3310392/shadertoy.zip)

**Comment by Malacath-92** [comment] 2019-06-21 10:08
The third shader is only a problem of us having the first frame on `iFrame == 1` instead of `iFrame == 0`, if you thus rewrite the shader to test against that instead of `iFrame < 1` it will work.
The second shader requires the same treatment, but it also seems to proc a bug in the extension, I will take a good look at that.

**Comment by Malacath-92** [comment] 2019-06-21 16:04
With the second example, some of the inputs are wrong, i.e. not corresponding to the same shaders as they do on the online version, which you can fix yourself.
Then the noise texture used for some randomness in the particles is missing, which causes some unexpected behavior, so for the time being I just disabled that line.
Most importantly though, the extension bugs out on circular dependencies of, which afaik happened here only because of the first point I mentioned. But a fix is incoming.

**Comment by Malacath-92** [comment] 2019-06-21 16:08
Thanks for opening this issue @yafacex 
Those were some of the most complex shaders this extension has seen in my testing, so it helped a lot  😃

**Comment by Malacath-92** [comment] 2019-07-07 18:27
Closing this since @yafacex didn't report any more issues.

**Closed by Malacath-92** 2019-07-07 18:27 UTC
