### ISSUE TITLE
GLSL viewer suddenly not loading

### ISSUE THREAD

**Issue by ianacaburian** [stevensona/shader-toy#45] opened 2019-03-30 17:08 UTC
Hey there, see image below. This happens after trying to open the GLSL viewer on a file that has worked previously. As you can see there is no error log displayed as usual - only grey boxes. Not sure what else to try or where to go from here. Thanks in advance for the help.

<img width="1166" alt="Screen Shot 2019-03-31 at 4 03 13 am" src="https://user-images.githubusercontent.com/35755724/55279234-4f162180-536a-11e9-9f9d-c0b4a9d3d670.png">

**Comment by Malacath92** [comment] 2019-03-31 15:16
Does this happen for any shader for you? If not, can you produce a minimum working example.
Which platform are you on?
Which version of VS Code are you running?

**Comment by edap** [comment] 2019-04-04 09:25
This is also happening to me. Any shader has the same output. Even a dummy:

```
vec2 vectorField(vec2 uv){
  vec2 res = uv;
  res.x += sin(res.y*30.5) * 0.01;
  return res;
}

void main(){
  vec2 st = gl_FragCoord.xy / iResolution.xy;
  st.y *= iResolution.y / iResolution.x;
  st = vectorField(st);

  vec3 col = vec3(1.0,0.,0.) * step(st.x, 0.5);
  gl_FragColor = vec4(col,1.0);
}
```

Produce the same result as @ianacaburian was posting.

**Comment by uniformfake** [comment] 2019-04-06 05:26
I have the same symptoms.

I am on Mac0S Mojave 10.14.4 / VSCode 1.33

**Comment by nickkuk** [comment] 2019-04-06 06:10
Ubuntu Linux / VSCode 1.33 - the same.

**Comment by Malacath-92** [comment] 2019-04-07 08:09
This is a bummer. Presumably the last version, which did some major refactoring introduced a bug. I will invest some time looking at some Linux I have available to see what's happening. Unfortunately I don't have any access to a Mac so that's a bit difficult for me to fix, we can only hope that the issues on Linux are the same as the Mac ones  😅 
Otherwise, @stevensona do you have the possibility to look into this on Mac OS?

**Comment by Malacath-92** [comment] 2019-04-07 10:05
I think the issue is only a path issue that we didn't handle correctly. If you have a chance to test #46 it would be greatly appreciated. I tested on Ubuntu 18.10, though didn't have WebGL available. But it seemed the core issue, which was that the WebView wasn't able to load resources, is fixed at least on Linux systems, presumably also on MacOS.

**Comment by Malacath-92** [comment] 2019-04-07 18:16
@ianacaburian This change is now live, let us know if it is fixed now or not.

**Comment by ianacaburian** [comment] 2019-04-07 21:12
Hey guys, I tested the new version 0.82 and still had the same problem. So I thought I'll try updating VS Code. It was already up to date but it gave me a message "Unable to perform update on read-only volume." My app was still located in a folder other than Applications. After moving VS Code to Applications, the extension works fine now. So a bit inconclusive as to whether the new commits fixed anything but there you go.

**Comment by Malacath-92** [comment] 2019-04-08 05:38
Interesting 😄 
Can some one else see if the issue is fixed with the newest version?
@uniformfake @edap @nickkuk

**Comment by nickkuk** [comment] 2019-04-08 06:18
@Malacath-92, thanks! Shader works now, but textures don't load without any warnings.
I tried both
```
#iChannel0 file://./texture.png
```
and .vscode/settings.json with
```json
{
  "shader-toy.textures": {
    "0": "file://./texture.png",
  }
}
```

**Comment by Malacath-92** [comment] 2019-04-09 07:27
It looks like I have some commits that didn't make it into the PR and should fix this. I'll make a new PR as soon as I get home.

**Comment by nickkuk** [comment] 2019-04-11 05:45
@Malacath-92, textures work in 0.8.3 now. Thanks!

**Closed** 2019-04-15 15:57 UTC
Labels: bug
