### ISSUE TITLE
Restart of VS Code is required to reset the preview with the current shader file.

### ISSUE THREAD

**Issue by domske** [stevensona/shader-toy#50] opened 2019-05-08 22:06 UTC
Restart of VS Code is required to reset the preview with the current shader file.
If I open the shader preview with a working shader (no errors), it's not possible to open another glsl-file for the preview. The preview still shows the first shader.

Reproduce:
1. Open a glsl-file.
2. Show preview tab.
3. Change the file / Switch to another file.

Result: The preview does not switch to the selected file. Also after closing the tab and reopen with command. It does only work if I restart VS Code. 
Summary, the preview does only work for the first previewed file.

Extension Version: 0.8.3
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by Malacath-92** [comment] 2019-05-09 05:45
Can you check your settings and see if "shader-toy.reloadOnEditTextDelay" is set to "false" . In the GUI for settings you will find this under Extensions->Shader-Toy->Reload On Change Editor.
If it is set to false, try setting it to true and see if at least half of your problem. I will check if I can reproduce the issue regarding re-running the command.

**Comment by domske** [comment] 2019-05-09 07:08
The option "Reload On Change Editor" should be set to true. Thanks for the hint.
Maybe this option should by default set to `true`? 

```json
"shader-toy.reloadOnChangeEditor": true
```

**Comment by Malacath-92** [comment] 2019-05-09 07:10
Possibly the option should be set to true, we can think about that for the next release.

Reopening because the issue of not being able to load another file explicitly still exists.

**Comment by Malacath-92** [comment] 2019-05-09 07:42
I'm not sure I know what you mean.
- If you close the text-editor-tab and reopen it, the content of your shader would not change, so the preview should not need to reload.
- If you close the preview-tab and reopen it via the command, then the corresponding shader of your active editor should be previewed.
- If you rerun the command, irrespective of the current previewed shader, then the corresponding shader of your active editor should be previewed.

That's the behavior I would expect and consider reasonable UX. The fact that points 2 and 3 are not functional r/n is a bug, hence I reopened the issue.
Are we talking about the same issue then?

**Comment by Malacath-92** [comment] 2019-05-25 06:13
Should be fixed by #48

**Closed by Malacath-92** 2019-05-25 06:13 UTC
